packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all packages in direct subdirs of packages/
  - "components/*"
  # exclude packages that are inside test directories
  - "!**/test/**"
